spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:users_db
    driver-class-name: org.h2.Driver
    username: users
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
        data-locations: classpath:create_users.sql, classpath:insert_users.sql
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

springdoc:
  packages-to-scan: com.practice.spring.h2
  paths-to-match: /**
  api-docs:
    path: /api-docs